spring.application.name=notice

# 데이터베이스 연결 URL (3306은 MySQL 기본 포트입니다)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# 사용할 드라이버 클래스 지정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate 설정 (콘솔에서 SQL 쿼리를 예쁘게 보기 위함)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

# 파일 업로드 전송 방식에 따른 최대 용량 제한
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# 파일 업로드 경로
file.upload.path=uploads/board